### ISSUE TITLE
crashes on test

### ISSUE THREAD

**Issue by anagtz** [Arkadiy-Garber/MHCscan#1]
Hi,
I'm very interested in using your pipeline but can't get it to work. So far, two different people in my lab have tried to install it and use it on two different computers, and we get the same error.

We installed it via conda as indicated in your readme file and tested it like this (after activating the conda environment):
MHCscan.sh -i MAG1.faa -g MAG1.gff -o MAG1_MHCscan.csv -t 32 --prot

First, we get the error:
```
--Skipping Prodigal
/mnt/storage/software/conda_env/mhcscan/MHCscan/bin/remove_asterisk.py:12: DeprecationWarning: ssl.PROTOCOL_TLSv1 is deprecated
  gcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
Phobius ver 1.01
(c) 2004 Lukas Kall, Anders Krogh, Erik Sonnhammer

Use of uninitialized value $predstr in concatenation (.) or string at /mnt/storage/software/conda_env/mhcscan/MHCscan/bin/phobius.pl line 262, <SOUT> line XXXX.
Use of uninitialized value $predstr in concatenation (.) or string at /mnt/storage/software/conda_env/mhcscan/MHCscan/bin/phobius.pl line 249, <SOUT> line XXXX.
```
it was repeated many times (one error per protein in the input fasta file).

After, these errors follow:
```
/mnt/storage/software/conda_env/mhcscan/MHCscan/bin/MHCscan.sh: line 89: cytoscan.py: command not found
Could not find conda environment: hhsuite_env
You can list all discoverable environments with `conda info --envs`.

Traceback (most recent call last):
  File "/mnt/storage/software/conda_env/mhcscan/MHCscan/bin/mhc_annotate.py", line 379, in <module>
    ID = ls[8].split(args.id + "=cds-")[1].split(";")[0]
IndexError: list index out of range
```
command "locate cytoscan.py" gives nothing back so maybe the file is missing?

Can you please help us deal with these errors so we can test your pipeline?

Thanks in advance,
Ana

**Comment by Arkadiy-Garber** [comment]
Hi Ana,

Thanks for your interest in this program! Sorry you're having issues. The first error you posted (`Use of uninitialized value`) is not consequential as it is always produced by the Phobius dependency, even when the program runs successfully. I havent figured out how to turn that off.

The second error suggests that the setup installation did not complete as expected. Could you confirm that you are running this command under the created conda environment? The conda environment is entered by running `conda create -n mhcscan` before you run the program.

Thanks,
Arkadiy

**Comment by anagtz** [comment]
Hi Arkadiy,

Yes, I had previously created the environment as instructed in your Readme file
I just loaded it again with `conda activate mhcscan` and then ran a test with a MAG `MHCscan.sh -i Proteome/FAAs/MAG1.faa -g Proteome/GFFs/MAG1.gff -o MAG1_MHCscan.csv -t 32 --prot`
The error is still the same:(

````
Use of uninitialized value $predstr in concatenation (.) or string at /home/ana/LAB/Programs/MHCscan/bin/phobius.pl line 262, <SOUT> line 64239.
/home/ana/LAB/Programs/MHCscan/bin/MHCscan.sh: line 89: cytoscan.py: command not found

EnvironmentNameNotFound: Could not find conda environment: hhsuite_env
You can list all discoverable environments with `conda info --envs`.


Traceback (most recent call last):
  File "/home/ana/LAB/Programs/MHCscan/bin/mhc_annotate.py", line 379, in <module>
    ID = ls[8].split(args.id + "=cds-")[1].split(";")[0]
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
(mhcscan) ana@Amate:~/LAB/Chile22/Metagenomes/MAGs/CH22-ROJ$ 
````

Thanks a lot:)

**Comment by TianzeS** [comment]
> Hi Ana,
> 
> Thanks for your interest in this program! Sorry you're having issues. The first error you posted (`Use of uninitialized value`) is not consequential as it is always produced by the Phobius dependency, even when the program runs successfully. I havent figured out how to turn that off.
> 
> The second error suggests that the setup installation did not complete as expected. Could you confirm that you are running this command under the created conda environment? The conda environment is entered by running `conda create -n mhcscan` before you run the program.
> 
> Thanks, Arkadiy

Hi Arkadiy,
I think this is a cool tool however with some fatal errors cause this impossible to run.
1. Please kindly notice that in your github repo, there isn't a cytoscan.py script, that is why Ana got: MHCscan.sh: line 89: cytoscan.py: command not found
2. Please kindly notice in the install guide you give build us a conda env called mhcscan. However, in your MHCscan.sh, it writes "conda activate hhsuite_env", that will cuase the another error that Ana metioned before. EnvironmentNameNotFound: Could not find conda environment: hhsuite_env.

Best regards,
Tianze

**Comment by Middle-Author-Bioinformatics** [comment]
Hi Tianze,

Thank you for your attention to this matter - we will address these issues within the next few weeks.

In the meantime, please feel free to run MHCScan on a free web server that we just released: [https://omix.midauthorbio.com/](https://omix.midauthorbio.com/).

Thanks,
Arkadiy

**Comment by TobiasWinter97** [comment]
> Hi Tianze,
> 
> Thank you for your attention to this matter - we will address these issues within the next few weeks.
> 
> In the meantime, please feel free to run MHCScan on a free web server that we just released: https://omix.midauthorbio.com/.
> 
> Thanks, Arkadiy

Hi Middle-Author-Bioinformatics,

I would also like to know have you fix the bug?

**Comment by Middle-Author-Bioinformatics** [comment]
Hi Sammy,

Are you interested in running this locally (i.e. on many genomes at once)?

Thanks,
Arkadiy

**Comment by TobiasWinter97** [comment]
> Hi Sammy,
> 
> Are you interested in running this locally (i.e. on many genomes at once)?
> 
> Thanks, Arkadiy

Yes, I would like to run multiple genome at once locally!

**Comment by anagtz** [comment]
Hi, I'm very interested in solving this issue and using this tool to explore my data. However, it is not a good moment now for me to look back on this data (I requested help in October 2024). I hope I can get back to this soon and solve the issue.

**Comment by TobiasWinter97** [comment]
> Hi, I'm very interested in solving this issue and using this tool to explore my data. However, it is not a good moment now for me to look back on this data (I requested help in October 2024). I hope I can get back to this soon and solve the issue.

Hi, Ana. Can you tell me finally what method or which software you used to predict  MHC? Thanks!
